db.auth("jimmie","");
db.cusin_subscription.find().skip(400000).limit(1000000).forEach( 
    function(i) {
    db.xtas_subscription.insert( {
        agreementid: "",
        agreementnumber: "",
        agreement: "",
        contractingparty: "",
        typeofmainfunction: "",
        mainfunctioncode: "",
        mainfunctionname: "",
        companyorganisationnumber: "",
        companyname: "",
        customername: "",
        costlocationname: "",
        employeename: "",
        subscriptionid: "",
        directsubscription: "",
        constructionnumber: "",
        mobilenumber: i.subscriptionnumber,
        imei: "",
        subscriptionname: "",
        subscriptionnumber: "",
        fromsystem: "",
        extractdate: "",
        filename: "",
        dtime: "",
        ctime: "",
        mtime: "",
        subscriptionstatus: "",
        billingaccountnumber: "",
        subscriptionzipcode: "",
        subscriptioncity: "",
        subscriptioncountry: "",
        subscriptionaddress: "",
        subscribername: "",
        customertype: "",
        startdate: "",
        categoryid: "",
        categoryname: "",
        c2bcacheuid: "",
        implementedproductcode: "",
        implementedproductname: "",
        slaid: "",
        priority: "",
        subscriptioncoaddress: "",
        slcode1: "",
        slcode2: "",
        slcode3: "",
        slcode4: "",
        subscriptionpointid: "",
        carrierid: "",
        subscriptionidtag: "",
        subscriptionid2: "",
        typeofservicedesk: "",
        custheader_subinfo1: "",
        custheader_subinfo2: "",
        custheader_subinfo3: "",
        custheader_subinfo4: "",
        subscriptioninfo1: "",
        subscriptioninfo2: "",
        subscriptioninfo3: "",
        subscriptioninfo4: ""
    })
});
db.xtas_subscription.createIndex( { mobilenumber: 1 } )